name: Build and Deploy project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
      
      - name: Make build.sh executable
        run: chmod +x ./scripts/build.sh

      - name: Run build script
        run: ./scripts/build.sh

      - name: Create zip file for Lambda function
        run: cd lambda/dist && zip -r ../../function.zip . && cd ../../

      - name: Upload Lambda zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: function.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Lambda artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-zip
      
      - name: Download Lambda zip artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-zip  # This downloads the artifact named 'lambda-zip' and extracts function.zip
    
      - name: Make deployLambda.sh executable
        run: chmod +x ./scripts/deployLambda.sh

      - name: Deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: ./scripts/deployLambda.sh VectorConverter function.zip